project:
  type: book

execute:
  freeze: auto

book:
  title: "MPA Europe - OBIS contribution documentation"
  author: "Pieter Provoost, Silas Principe, MPA Europe team"
  date: "2023"
  #downloads: [pdf, epub]
  #doi: "10.XXX/XXX"
  #url: https://example.com
  #repo-url: https://github.com/juba/bookup-html/tree/main/examples/book
  #repo-actions: edit
  search: true
  reader-mode: true
  sidebar:
    style: "docked"
  chapters:
    - index.qmd
    - part: "Content"
      chapters:
        - studyarea.qmd
        - datadownload.qmd
        - datamining.qmd
  # appendices:
  #   - references.qmd

#bibliography: references.bib

format:
  bookup-html